sotm_2025:
  id: sotm_2025
  alt: State of the Map 2025
  link: https://2025.stateofthemap.org
  img: banners/sotm_2025.png
  srcset:
    - [banners/sotm_2025.png, 1x]
    - [banners/sotm_2025@2x.png, 2x]
  startdate: 2025-jul-01
  enddate: 2025-oct-05
